{
 "title": "Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Streamlit Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "streamlit_app_log_errors_created{job=\"streamlit-metrics\"}",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Streamlit Button Clicks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "streamlit_button_clicks_created",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FastAPI HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "FastAPI GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "python_gc_collections_total", "legendFormat": "__auto" }
   ]
  }
 ]
}